### ISSUE TITLE
AWS accounts beginning in 0 generate error at line 190

### ISSUE THREAD

**Issue by garbacik** [PaloAltoNetworks/pcs-sizing-scripts#18]
## Describe the bug
If an AWS account within an organization begins with a zero, it reports an error at line 190 in the aws/resource-count-aws.sh.as follows:
./resource-count-aws.sh: line 190: [[: 012345678983: value too great for base (error token is "012345678983")

## Expected behavior
Value is the test should be their string equivalent. 

## Current behavior

./resource-count-aws.sh: line 190: [[: 012345678983: value too great for base (error token is "012345678983")

## Possible solution
Remove the double bracket test and use single brackets. See https://stackoverflow.com/questions/24777597/value-too-great-for-base-error-token-is-08

## Steps to reproduce
At line 189, insert something like: ACCOUNT_ID=012345678983

**Comment by tkishel** [comment]
Please take a look at PR #19

**Comment by tkishel** [comment]
PR Merged
