### ISSUE TITLE
Update AWS sizing script to include a "--compute" parameter rather than 2 separate scripts

### ISSUE THREAD

**Issue by sullivan1337** [PaloAltoNetworks/pcs-sizing-scripts#23]
### Is your feature request related to a problem?

Ease of use

### Describe the solution you'd like

The AWS sizing script should have a "--compute" flag rather than be 2 separate scripts

### Describe alternatives you've considered

There are currently 2 scripts as a workaround

**Comment by tkishel** [comment]
Addressed via #25
